name: CI
on: [push, pull_request]
jobs:
  specs:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu, macos, windows ]
        ruby: [ 2.6.8, 2.7.4, 3.0.2 ]
    runs-on: ${{ matrix.os }}-latest
    steps:
    - name: git config autocrlf
      run: git config --global core.autocrlf false
      if: matrix.os == 'windows'

    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler: none
    - name: Clone MSpec
      run: git clone https://github.com/ruby/mspec.git ../mspec

    - name: Run specs (Linux)
      if: matrix.os == 'ubuntu'
      env:
        CHECK_LEAKS: true
      run: ../mspec/bin/mspec --timeout 30

    - name: Run specs (macOS)
      if: matrix.os == 'macos'
      env:
        CHECK_LEAKS: true
      # Use a larger timeout on macOS since it seems to have less reliable performance
      run: ../mspec/bin/mspec --timeout 90

    - name: Run specs (Windows)
      if: matrix.os == 'windows'
      env:
        CHECK_LEAKS: true
      run: |
        # Actions uses UTF8, causes test failures, similar to normal OS setup
        [Console]::OutputEncoding = [System.Text.Encoding]::GetEncoding("IBM437")
        [Console]::InputEncoding  = [System.Text.Encoding]::GetEncoding("IBM437")
        ../mspec/bin/mspec -j

    - name: Run C-API specs as C++
      if: matrix.os != 'windows'
      env:
        SPEC_CAPI_CXX: true
      run: ../mspec/bin/mspec :capi

  rubocop:
    name: RuboCop
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
    - run: gem install rubocop:0.77.0
    - run: rubocop --parallel
